#!/bin/bash
################################
# Swift Bash Functions Library #
################################
SBFL_VERSION="0.0.1"

#
# Do not edit this file. Just source it into your script
# and override the variables to change their value.
#

################################################################################
# Private functions. Don't call then from outside
################################################################################
AUTH_URL_CLODO="http://testapi.clodo.ru/v1"

function init() {
    DEBUG=no
    AUTH_URL=$AUTH_URL_CLODO
}

################################################################################
# Public Functions
################################################################################

#
# Authenticates in $AUTH_URL and updates API_URL ans API_TOKEN
# Args: Storage user 
#       Storage key
#
function authenticate() {
    STORAGE_USER=$1
    STORAGE_KEY=$2
    
    AUTH_DAT="$(curl -I -s -H "X-Auth-User: $STORAGE_USER" -H "X-Auth-Key: $STORAGE_KEY" $AUTH_URL)"
    
    if [ -z "$AUTH_DAT" ]; then
        echo "ERROR: Can't find Cloud Storage server"
        return -2
    fi

    ERR=`echo "$AUTH_DAT" | grep 'Unauthorized'`
    if [ $? -eq 0 ]; then
        echo "ERROR: Unauthorized!"
        return -3
    fi

    API_URL=`echo "$AUTH_DAT" | grep 'X-Storage-Url'|sed 's/X-Storage-Url: \(.*\)\r/\1/'`
    if [ -z "$API_URL" ]; then
        echo "ERROR: Error getting API URL"
        return -2
    fi

    API_TOKEN=`echo "$AUTH_DAT" | grep 'X-Storage-Token' | sed 's/X-Storage-Token: \(.*\)\r/\1/'`
    if [ -z "$API_TOKEN" ]; then
        echo "ERROR: Error getting API TOKEN"
        return -2
    fi
    return 0
}

#
# Get Account storage usage
#
function get_acct_bytes_used() {
    curl -I -s -X HEAD -H "X-Auth-Token: $API_TOKEN" $API_URL |  grep "X-Account-Bytes-Used:" | cut -f2 -d" "
}

#
# Get Acccount container count
#
function get_acct_cont_count() {
    curl -I -s -X HEAD -H "X-Auth-Token: $API_TOKEN" $API_URL |  grep "X-Account-Container-Count:" | cut -f2 -d" "
}

#
# Get Account MetaData 
#
function get_acct_meta() {
    curl -I -s -X HEAD -H "X-Auth-Token: $API_TOKEN" $API_URL |  grep "X-"
}

#
# List account containers
#
function get_cont_list() {
    suffix=""
    if [ "$1" == "json" -o "$1" == "xml" ]; then
        suffix="?format=$1"
    fi
    curl -s -X GET -H "X-Auth-Token: $API_TOKEN" ${API_URL}${suffix}
}

#
# Get Container MetaData 
#
function get_cont_meta() {
    cont="$1"
    if [ -z "$1" ]; then
        return
    fi

    curl -I -s -X HEAD -H "X-Auth-Token: $API_TOKEN" $API_URL/$cont |  grep "X-"
}


#
# List container objects
#
function get_obj_list() {
    cont="$1"
    if [ -z "$1" ]; then
        return
    fi
    
    suffix=""
    if [ "$2" == "json" -o "$2" == "xml" ]; then
        suffix="?format=$2"
    fi
    curl -s -X GET -H "X-Auth-Token: $API_TOKEN" ${API_URL}/$cont${suffix}
}

#
# Create container
#
function create_cont() {
    cont="$1"
    if [ -z "$1" ]; then
        return
    fi
    RESP=$(curl -s -X PUT -D - -H "X-Auth-Token: $API_TOKEN" ${API_URL}/$cont)
    if echo $RESP | grep -o "201" > /dev/null ; then
        return 0
    else
        return -2
    fi
}

#
# Delete container
#
function delete_cont() {
    cont="$1"
    if [ -z "$1" ]; then
        return
    fi
    RESP=$(curl -s -X DELETE -D - -H "X-Auth-Token: $API_TOKEN" ${API_URL}/$cont)
    if echo $RESP | grep -o "201" > /dev/null ; then
        return 0
    else
        return -2
    fi
}



init

