#!/bin/bash
################################
# Swift Bash Functions Library #
################################
SBFL_VERSION="0.0.2"

#
# Do not edit this file. Just source it into your script
# and override the variables to change their value.
#

################################################################################
# TODO:
# - Reauth cycle with wrong token may never end
# * Huge file uploads part by part should be implemented
# * Meta-data operations should be implemented
# * Add Debug output if $DEBUG is 'yes'
# * Move auth check to common function
# * Add status return function printing ...OK, ...ERR, etc
# * Add 500 errors processing
# * Write smoke tests =)
#
#
################################################################################

################################################################################
# Private functions. Don't call them from outside
################################################################################
AUTH_URL_CLODO="http://testapi.clodo.ru/v1"

LIST_LIMIT=10000

function init() {
    DEBUG=no
    AUTH_URL=$AUTH_URL_CLODO
}

################################################################################
# Public Functions
################################################################################

#
# Authenticates in $AUTH_URL and updates API_URL ans API_TOKEN
# Args: Storage user 
#       Storage key
#
function authenticate() {
    STORAGE_USER=$1
    STORAGE_KEY=$2
    
    AUTH_DAT="$(curl -I -s -H "X-Auth-User: $STORAGE_USER" -H "X-Auth-Key: $STORAGE_KEY" $AUTH_URL) 2>&1"
    
    if [ -z "$AUTH_DAT" ]; then
        echo "ERROR: Can't find Cloud Storage server"
        return -2
    fi

    ERR=`echo "$AUTH_DAT" | grep 'Unauthorized'`
    if [ $? -eq 0 ]; then
        echo "ERROR: Unauthorized!"
        return -3
    fi

    API_URL=`echo "$AUTH_DAT" | grep 'X-Storage-Url'|sed 's/X-Storage-Url: \(.*\)\r/\1/'`
    if [ -z "$API_URL" ]; then
        echo "ERROR: Error getting API URL"
        return -2
    fi

    API_TOKEN=`echo "$AUTH_DAT" | grep 'X-Storage-Token' | sed 's/X-Storage-Token: \(.*\)\r/\1/'`
    if [ -z "$API_TOKEN" ]; then
        echo "ERROR: Error getting API TOKEN"
        return -2
    fi
    return 0
}

#
# Get Account storage usage
#
function get_acct_bytes_used() {
    curl -I -s -X HEAD -H "X-Auth-Token: $API_TOKEN" $API_URL |  grep -o -E "X-Account-Bytes-Used: [0-9]+" | cut -f2 -d" "
}

#
# Get Acccount container count
#
function get_acct_cont_count() {
    curl -I -s -X HEAD -H "X-Auth-Token: $API_TOKEN" $API_URL |  grep -o -E "X-Account-Container-Count: [0-9]+" | cut -f2 -d" "
}

#
# Get Account MetaData 
#
function get_acct_meta() {
    curl -I -s -X HEAD -H "X-Auth-Token: $API_TOKEN" $API_URL |  grep "X-"
}

#
# List account containers
#
function get_cont_list() {
    suffix=""
    if [ "$1" == "json" -o "$1" == "xml" ]; then
        suffix="?format=$1"
    fi
    curl -s -X GET -H "X-Auth-Token: $API_TOKEN" ${API_URL}${suffix}
}

#
# Get Container MetaData 
#
function get_cont_meta() {
    cont="$1"
    if [ -z "$cont" ]; then
        return
    fi

    curl -I -s -X HEAD -H "X-Auth-Token: $API_TOKEN" $API_URL/$cont |  grep "X-"
}

#
# Get container's object count
#
function get_obj_count() {
    cont="$1"
    if [ -z "$cont" ]; then
        return
    fi

    get_cont_meta $cont | grep -o -E "X-Container-Object-Count: [0-9]+" | cut -f2 -d" "
}

#
# List container objects
#
function get_obj_list() {
    cont="$1"
    if [ -z "$cont" ]; then
        return
    fi
    
    suffix=""
    if [ "$2" == "json" -o "$2" == "xml" ]; then
        suffix="?format=$2"
    fi
    curl -s -X GET -H "X-Auth-Token: $API_TOKEN" ${API_URL}/$cont${suffix}
}

#
# List all container's object and output to file
#
function long_obj_list_2file() {
    cont="$1"
    if [ -z "$cont" ]; then
        return
    fi
    
    prefix="$2"   
    if [ -z "$prefix" ]; then
        return
    fi

    file="$3"
    if [ -f $file ]; then
        echo -ne "" > $file
    fi

    limit=$LIST_LIMIT
    marker=""

    while [ $limit -gt 0 ]
    do
        LIST=`curl -s -X GET -H "X-Auth-Token: $API_TOKEN" ${API_URL}/$cont${suffix}\?limit=${limit}\&marker=${marker}`
        lcnt=`echo "$LIST" | wc -l`
        marker=`echo "$LIST" |  tail -n1`
        if [ $lcnt -lt $limit ]; then
            limit=0
        fi
        echo "$LIST" >> $file
    done
}

#
# Create container
#
function create_cont() {
    cont="$1"
    if [ -z "$cont" ]; then
        return
    fi
    RESP=$(curl -v -X PUT -D - -H "X-Auth-Token: $API_TOKEN" ${API_URL}/$cont 2>&1)
 
    if echo "$RESP" | grep -E "< HTTP/1.. 204|< HTTP/1.. 201|< HTTP/1.. 202" > /dev/null ; then
        return 0
    elif echo $RESP | grep -E "< HTTP/1.. 401" > /dev/null ; then
        authenticate $STORAGE_USER $STORAGE_KEY
        create_cont "$cont"
        return $?
    elif echo $RESP | grep -E "< HTTP/1.. 404" > /dev/null ; then
        return -2
    else
        return -1
    fi
}

#
# Delete container
#
function delete_cont() {
    cont="$1"
    if [ -z "$cont" ]; then
        return
    fi
    RESP=$(curl -v -X DELETE -D - -H "X-Auth-Token: $API_TOKEN" ${API_URL}/$cont 2>&1)

    if echo $RESP | grep -E "< HTTP/1.. 204|< HTTP/1.. 201|< HTTP/1.. 202" > /dev/null ; then
        return 0
    elif echo $RESP | grep -E "< HTTP/1.. 401" > /dev/null ; then
        authenticate $STORAGE_USER $STORAGE_KEY
        delete_cont "$cont"
        return $?
    elif echo $RESP | grep -E "< HTTP/1.. 404" > /dev/null ; then
        return -2
    else
        return -1
    fi
}

#
# Create or update object
#
function put_obj() {
    cont="$1"
    if [ -z "$cont" ]; then
        return
    fi
    
    obj="$2"
    if [ -z "$obj" ]; then
        return
    fi

    file="$3"
    if [ -z "$file" ]; then
        return
    fi
    
    RESP=$(curl -0 -I -v -X PUT -T $file -H "X-Storage-Token: $API_TOKEN" ${API_URL}/${cont}/${obj} 2>&1) 

    if echo $RESP | grep -E "< HTTP/1.. 204|< HTTP/1.. 201|< HTTP/1.. 202" > /dev/null ; then
        return 0
    elif echo $RESP | grep -E "< HTTP/1.. 401" > /dev/null ; then
        authenticate $STORAGE_USER $STORAGE_KEY
        put_obj "$cont" "$obj" "$file"
        return $?
    elif echo $RESP | grep -E "< HTTP/1.. 404" > /dev/null ; then
        return -2
    else
        return -1
    fi
}

#
# Copy object
#
function copy_obj() {
    src="$1"
    if [ -z "$src" ]; then
        return
    fi
    
    dest="$2"
    if [ -z "$dest" ]; then
        return
    fi

    RESP=$(curl -0 -v -X PUT -H "X-Storage-Token: $API_TOKEN" \
        -H "X-Copy-From: $src" \
        -H "Content-Length: 0" \
        ${API_URL}/${dest} 2>&1) 

    if echo $RESP | grep -E "< HTTP/1.. 204|< HTTP/1.. 201|< HTTP/1.. 202" > /dev/null ; then
        return 0
    elif echo $RESP | grep -E "< HTTP/1.. 401" > /dev/null ; then
        authenticate $STORAGE_USER $STORAGE_KEY
        copy_obj "$src" "$dest"
        return $?
    elif echo $RESP | grep -E "< HTTP/1.. 404" > /dev/null ; then
        return -2
    else
        return -1
    fi
}

#
# Delete object
#
function delete_obj() {
    obj="$1"
    if [ -z "$obj" ]; then
        return
    fi
    RESP=$(curl -v -X DELETE -D - -H "X-Auth-Token: $API_TOKEN" ${API_URL}/$obj 2>&1)
    if echo $RESP | grep -E "< HTTP/1.. 204|< HTTP/1.. 201|< HTTP/1.. 202" > /dev/null ; then
        return 0
    elif echo $RESP | grep -E "< HTTP/1.. 401" > /dev/null ; then
        authenticate $STORAGE_USER $STORAGE_KEY
        delete_obj "$obj"
        return $?
    elif echo $RESP | grep -E "< HTTP/1.. 404" > /dev/null ; then
        return -2
    else
        return -1
    fi
}

#
# Create pseudo-directory object
#
function create_dir() {
    cont="$1"
    if [ -z "$cont" ]; then
        return
    fi

    obj="$2"
    if [ -z "$obj" ]; then
        return
    fi
    RESP=$(curl -0 -f -X PUT -v -H "X-Storage-Token: $API_TOKEN" -H "Content-Type: application/directory" -H "Content-Length: 0" $API_URL/${cont}/${obj} 2>&1)

    if echo $RESP | grep -E "< HTTP/1.. 204|< HTTP/1.. 201|< HTTP/1.. 202" > /dev/null ; then
        return 0
    elif echo $RESP | grep -E "< HTTP/1.. 401" > /dev/null ; then
        authenticate $STORAGE_USER $STORAGE_KEY
        create_dir "$cont" "$obj"
        return $?
    elif echo $RESP | grep -E "< HTTP/1.. 404" > /dev/null ; then
        return -2
    else
        return -1
    fi
}

init

